# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HiddenGems' do

pod 'Alamofire', '~> 3.0'
pod 'AWSS3'
pod 'AWSCognito'
pod 'Kingfisher', '~> 2.2'
pod 'MediumMenu'

end

